-- ADD SOCIAL MEDIA LINK FIELDS TO PROFILES
-- RUN THIS IN THE SUPABASE SQL EDITOR TO ENABLE SOCIAL MEDIA LINKS

ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS facebook_url TEXT,
ADD COLUMN IF NOT EXISTS instagram_url TEXT,
ADD COLUMN IF NOT EXISTS twitter_url TEXT,
ADD COLUMN IF NOT EXISTS tiktok_url TEXT;

-- RELOAD SCHEMA CACHE
NOTIFY pgrst, 'reload schema';
