-- ADD STORE AND PRO MEMBER FIELDS TO PROFILES
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS store_name TEXT,
ADD COLUMN IF NOT EXISTS store_description TEXT,
ADD COLUMN IF NOT EXISTS store_logo TEXT,
ADD COLUMN IF NOT EXISTS store_banner TEXT,
ADD COLUMN IF NOT EXISTS is_pro BOOLEAN DEFAULT false;

-- RELOAD SCHEMA CACHE
NOTIFY pgrst, 'reload schema';
